pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        // Environment variables
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '123456789012'
        PROJECT = 'roboshop'

    }
    options {
        // Options
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        ansiColor('xterm')
    }
/*     parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    } */
    // Build section (Out of 3 sections: Pre-Build, Build, Post-Build)
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """                        
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 10-sg
                            terraform plan
                        """                        
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """                        
                    }
                }
            }
        }
        stage('Bastion EKS ACM') {
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        script {
                            build job: '20-bastion', 
                            propagate: false, # Do not fail this job if the downstream job fails
                            wait: false # Do not wait for the downstream job to finish             
                        }
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: '80-eks', 
                            propagate: false, # Do not fail this job if the downstream job fails
                            wait: false # Do not wait for the downstream job to finish
                        }
                    }
                }
                stage('Trigger ACM') {
                    steps {
                        script {
                            build job: '60-acm', 
                            propagate: false, # Do not fail this job if the downstream job fails
                            wait: false # Do not wait for the downstream job to finish
                        }
                    }
                }
                                 
            }
        }
        stage('Trigger ALB') {
            steps {
                script {
                    build job: '70-frontend-alb', 
                    propagate: false, # Do not fail this job if the downstream job fails
                    wait: false # Do not wait for the downstream job to finish
                }
            }
        }
 
    }

    // post section
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir() // Clean up our workspace
        }
        success { 
            echo 'Hello again! Success'
        }
        failure { 
            echo 'Hello again! Failure'
        }
    }
}