pipeline {
    agent {
        label 'AGENT-1'
    }
    environment {
        // Environment variables
        appVersion = ''
        REGION = 'us-east-1'
        ACC_ID = '123456789012'
        PROJECT = 'roboshop'

    }
    options {
        // Options
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds()
        timeout(time: 10, unit: 'MINUTES')
        ansiColor('xterm')
    }
/*     parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information about the person')
        booleanParam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['One', 'Two', 'Three'], description: 'Pick something')
        password(name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter a password')
    } */
    // Build section (Out of 3 sections: Pre-Build, Build, Post-Build)
    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 20-bastion
                            terraform init -reconfigure
                        """                        
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 20-bastion
                            terraform plan
                        """                        
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: ${REGION}) {
                        sh """
                            cd 20-bastion
                            terraform apply -auto-approve
                        """                        
                    }
                }
            }
        }
 
    }

    // post section
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir() // Clean up our workspace
        }
        success { 
            echo 'Hello again! Success'
        }
        failure { 
            echo 'Hello again! Failure'
        }
    }
}